// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwLQ4SzIaY9ZlQpKrcfU8B62FsXovtYFI',
    appId: '1:60644087584:web:72779097a5339e4c8b6945',
    messagingSenderId: '60644087584',
    projectId: 'members-app-5cd66',
    authDomain: 'members-app-5cd66.firebaseapp.com',
    databaseURL: 'https://members-app-5cd66-default-rtdb.firebaseio.com',
    storageBucket: 'members-app-5cd66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcjSGsuC2vgYkJRbtMUOW8XHO09ABJodU',
    appId: '1:60644087584:android:84fb3f93dc9232a88b6945',
    messagingSenderId: '60644087584',
    projectId: 'members-app-5cd66',
    databaseURL: 'https://members-app-5cd66-default-rtdb.firebaseio.com',
    storageBucket: 'members-app-5cd66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2GY0pcGJcFRfI0bABv_nCLW78cQTJ5bo',
    appId: '1:60644087584:ios:6cfd1342ac032ea58b6945',
    messagingSenderId: '60644087584',
    projectId: 'members-app-5cd66',
    databaseURL: 'https://members-app-5cd66-default-rtdb.firebaseio.com',
    storageBucket: 'members-app-5cd66.appspot.com',
    iosClientId: '60644087584-nfogb61cdvu2fo88ldrdp1q06ehdgugc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sceptixapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2GY0pcGJcFRfI0bABv_nCLW78cQTJ5bo',
    appId: '1:60644087584:ios:6cfd1342ac032ea58b6945',
    messagingSenderId: '60644087584',
    projectId: 'members-app-5cd66',
    databaseURL: 'https://members-app-5cd66-default-rtdb.firebaseio.com',
    storageBucket: 'members-app-5cd66.appspot.com',
    iosClientId: '60644087584-nfogb61cdvu2fo88ldrdp1q06ehdgugc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sceptixapp',
  );
}
